load option .
load error .
load memcache .
load mongodb .
load reservation-server .
load server-test .




--- rew in SERVER-TEST : test0 .
--- rew in SERVER-TEST : test1 .

--- search [ 10, 40 ] in SERVER-TEST : test1 =>! C .

search  in SERVER-TEST : test2 =>+  < server-id / thread-id : Thread | state : reservationFailed , clientId : client-id , sessionId : session-id >   C .


search  in SERVER-TEST : test3 =>! C .