mod MEMCACHE-TEST is 
    protecting MEMCACHE .
    protecting CONFIGURATION .

    ops testGet0 testGet1 testSet : -> Configuration .
    ops CLIENT-0 MEMCACHE-0 : -> Oid .

    op data : -> Map{String, String} .

    eq data =
        insert ("a", "A", 
            insert("b", "B", 
                insert("c", "C", empty)
            )
        ) .


    eq testGet0 =
        < MEMCACHE-0 : MemcacheServer | datastore : data >
        getRequest(CLIENT-0, MEMCACHE-0, 1, "a") .

    eq testGet1 =
        < MEMCACHE-0 : MemcacheServer | datastore : data >
        getRequest(CLIENT-0, MEMCACHE-0, 1, "z") .

    eq testSet =
        < MEMCACHE-0 : MemcacheServer | datastore : data >
        setRequest(CLIENT-0, MEMCACHE-0, 1, "d", "D") .

endm