mod SERVER-TEST is
    protecting RESERVATION-SERVER .



    ops test0 test1 : -> Configuration .


    ops client-0 server-0 memcache-0 mongodb-0 : -> Oid .

    
    *** a trvial request
    eq test0 = 
        reservationRequest(client-0, server-0, 0, "John Doe", 0, 0, 0, 0)
        < server-0 : ReservationServer | memcache : memcache-0 , mongodb : mongodb-0 >
        < memcache-0 : MemcacheServer | datastore : empty >
        < mongodb-0 : MongDBServer | reservationTable : empty , hotelTable : empty > .


    *** a valid request
    eq test1 = 
        reservationRequest(client-0, server-0, 0, "John Doe", 0, 0, 1, 1)
        < server-0 : ReservationServer | memcache : memcache-0 , mongodb : mongodb-0 >
        < memcache-0 : MemcacheServer | datastore : empty >
        < mongodb-0 : MongDBServer | reservationTable : empty , hotelTable : (hotel(0, 10), empty) > .





endm