load option .
load memcache .
load mongodb .
load reservation-server .


*** symbolic evaluation on one request scenario for testing model correctness
mod TEST is
    protecting RESERVATION-SERVER .



    


    vars client-0 server-0 memcache-0 mongodb-0 : Oid .
    vars C : Configuration .
    vars customer-name : String .
    vars session-id thread-counter in-date hotel-id room-count : Nat .

    
    *** a trvial request
    


    *** a valid request
    --- eq test1 = 
    ---     reservationRequest(client-0, server-0, 0, "John Doe", 0, 0, 1, 1)
    ---     < server-0 : ReservationServer | memcache : memcache-0 , mongodb : mongodb-0 >
    ---     < memcache-0 : MemcacheServer | datastore : empty >
    ---     < mongodb-0 : MongDBServer | reservationTable : empty , hotelTable : (hotel(0, 10), empty) > .

endm



search in TEST : 
    reservationRequest(client-0, server-0, session-id, customer-name, hotel-id, in-date, s(in-date), room-count)
    < server-0 : ReservationServer | memcache : memcache-0 , mongodb : mongodb-0, threadCounter : thread-counter >
    < memcache-0 : MemcacheServer | datastore : empty >
    < mongodb-0 : MongDBServer | reservationTable : empty , hotelTable : empty >
    =>! C .


